// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionsEF;

#nullable disable

namespace TransactionsEF.Migrations
{
    [DbContext(typeof(TransactionContext))]
    [Migration("20241114154338_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("TransactionsEF.Transaction", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 22.5f,
                            Description = " add videos",
                            ProcessedAt = new DateTime(2009, 6, 1, 13, 45, 30, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 12.5f,
                            Description = " add video",
                            ProcessedAt = new DateTime(2009, 6, 15, 13, 45, 11, 432, DateTimeKind.Unspecified).AddTicks(5111)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 23.1f,
                            Description = " Add videos",
                            ProcessedAt = new DateTime(2009, 7, 14, 13, 45, 21, 717, DateTimeKind.Unspecified).AddTicks(2232)
                        },
                        new
                        {
                            Id = 4,
                            Amount = 6.5f,
                            Description = " Add Videos",
                            ProcessedAt = new DateTime(2009, 6, 11, 13, 40, 50, 657, DateTimeKind.Unspecified).AddTicks(3231)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
